<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'slug' => 'forage-nguekokh-phase-1',
                'theme' => 'water', 'status' => 'ongoing',
                'goal_amount' => 4200000, 'collected_amount' => 2450000,
                'cover_image' => '/assets/puits.jpeg',
                'published_at' => '2026-01-12',
                'title' => ['fr' => 'Forage a Nguekokh - phase 1', 'en' => 'Nguekokh borehole - phase 1', 'ar' => 'بئر نغوكوخ - المرحلة 1'],
                'description' => ['fr' => "Premiere phase d'un forage equipe d'une pompe solaire pour desservir 450 familles.", 'en' => 'First phase of a solar-powered borehole serving 450 families.', 'ar' => 'المرحلة الأولى من بئر مزود بمضخة شمسية لخدمة 450 عائلة.'],
                'location' => ['fr' => 'Nguekokh, Senegal', 'en' => 'Nguekokh, Senegal', 'ar' => 'نغوكوخ، السنغال'],
                'beneficiary_label' => ['fr' => '450 familles', 'en' => '450 families', 'ar' => '450 عائلة'],
            ],
            [
                'slug' => 'forage-kaolack-secondaire',
                'theme' => 'water', 'status' => 'completed',
                'goal_amount' => 1900000, 'collected_amount' => 1900000,
                'cover_image' => '/assets/puits.jpeg',
                'published_at' => '2025-11-20',
                'title' => ['fr' => 'Forage secondaire a Kaolack', 'en' => 'Secondary borehole in Kaolack', 'ar' => 'بئر ثانوي في كاولاك'],
                'description' => ['fr' => "Pompage manuel installe sur un point d'eau existant pour reduire les distances.", 'en' => 'Manual pump installed on an existing water point.', 'ar' => 'مضخة يدوية مثبتة على نقطة مياه موجودة.'],
                'location' => ['fr' => 'Kaolack, Senegal', 'en' => 'Kaolack, Senegal', 'ar' => 'كاولاك، السنغال'],
                'beneficiary_label' => ['fr' => '200 familles', 'en' => '200 families', 'ar' => '200 عائلة'],
            ],
            [
                'slug' => 'forage-rural-maradi',
                'theme' => 'water', 'status' => 'upcoming',
                'goal_amount' => 5600000, 'collected_amount' => 0,
                'cover_image' => '/assets/puits.jpeg',
                'published_at' => '2026-09-01',
                'title' => ['fr' => 'Forage rural dans la region de Maradi', 'en' => 'Rural borehole in Maradi region', 'ar' => 'بئر ريفي في منطقة مارادي'],
                'description' => ['fr' => "Projet structurel d'acces a l'eau potable dans une zone rurale du Niger.", 'en' => 'Structural access to drinking water in rural Niger.', 'ar' => 'مشروع هيكلي للوصول إلى مياه الشرب في منطقة ريفية في النيجر.'],
                'location' => ['fr' => 'Maradi, Niger', 'en' => 'Maradi, Niger', 'ar' => 'مارادي، النيجر'],
                'beneficiary_label' => ['fr' => '600 familles', 'en' => '600 families', 'ar' => '600 عائلة'],
            ],
            [
                'slug' => 'soutien-scolaire-thies',
                'theme' => 'education', 'status' => 'ongoing',
                'goal_amount' => 2800000, 'collected_amount' => 1780000,
                'cover_image' => '/assets/educationn.jpeg',
                'published_at' => '2026-02-05',
                'title' => ['fr' => 'Soutien scolaire a Thies', 'en' => 'Educational support in Thies', 'ar' => 'دعم مدرسي في ثيس'],
                'description' => ['fr' => "Kits scolaires et cours de soutien pour 300 enfants de quartiers defavorises.", 'en' => 'School kits and tutoring for 300 children.', 'ar' => 'حقيبة مدرسية ودروس دعم لـ 300 طفل.'],
                'location' => ['fr' => 'Thies, Senegal', 'en' => 'Thies, Senegal', 'ar' => 'ثيس، السنغال'],
                'beneficiary_label' => ['fr' => '300 enfants', 'en' => '300 children', 'ar' => '300 طفل'],
            ],
            [
                'slug' => 'bibliotheque-mobile-diourbel',
                'theme' => 'education', 'status' => 'completed',
                'goal_amount' => 3600000, 'collected_amount' => 3600000,
                'cover_image' => '/assets/educationn.jpeg',
                'published_at' => '2025-09-15',
                'title' => ['fr' => 'Bibliotheque mobile Diourbel', 'en' => 'Mobile library Diourbel', 'ar' => 'مكتبة متنقلة في ديوربيل'],
                'description' => ['fr' => "Bibliotheque itinERante desservant 12 villages avec plus de 2000 ouvrages.", 'en' => 'Traveling library serving 12 villages with 2000+ books.', 'ar' => 'مكتبة متنقلة تخدم 12 قرية بأكثر من 2000 كتاب.'],
                'location' => ['fr' => 'Diourbel, Senegal', 'en' => 'Diourbel, Senegal', 'ar' => 'ديوربيل، السنغال'],
                'beneficiary_label' => ['fr' => '12 villages', 'en' => '12 villages', 'ar' => '12 قرية'],
            ],
            [
                'slug' => 'equipement-scolaire-zinder',
                'theme' => 'education', 'status' => 'upcoming',
                'goal_amount' => 4800000, 'collected_amount' => 0,
                'cover_image' => '/assets/educationn.jpeg',
                'published_at' => '2026-10-01',
                'title' => ['fr' => 'Equipement scolaire dans le Zinder', 'en' => 'School equipment in Zinder', 'ar' => 'تجهيز مدرسي في زيندر'],
                'description' => ['fr' => "Tables, bancs et fournitures pour 15 salles de classe dans le Zinder.", 'en' => 'Desks and supplies for 15 classrooms in Zinder.', 'ar' => 'طاولات ومقاعد ولوازم لـ 15 فصلاً دراسياً في زيندر.'],
                'location' => ['fr' => 'Zinder, Niger', 'en' => 'Zinder, Niger', 'ar' => 'زيندر، النيجر'],
                'beneficiary_label' => ['fr' => '600 eleves', 'en' => '600 students', 'ar' => '600 تلميذ'],
            ],
            [
                'slug' => 'consultations-mbour',
                'theme' => 'health', 'status' => 'ongoing',
                'goal_amount' => 3000000, 'collected_amount' => 1350000,
                'cover_image' => '/assets/about.jpeg',
                'published_at' => '2026-03-01',
                'title' => ['fr' => 'Consultations gratuites a Mbour', 'en' => 'Free consultations in Mbour', 'ar' => 'استشارات مجانية في مبور'],
                'description' => ['fr' => "Consultations generalistes et sensibilisation pour 500 personnes.", 'en' => 'General consultations and awareness for 500 people.', 'ar' => 'استشارات عامة وتوعية لـ 500 شخص.'],
                'location' => ['fr' => 'Mbour, Senegal', 'en' => 'Mbour, Senegal', 'ar' => 'مبور، السنغال'],
                'beneficiary_label' => ['fr' => '500 personnes', 'en' => '500 people', 'ar' => '500 شخص'],
            ],
            [
                'slug' => 'campagne-vaccination-kaffrine',
                'theme' => 'health', 'status' => 'completed',
                'goal_amount' => 2200000, 'collected_amount' => 2200000,
                'cover_image' => '/assets/about.jpeg',
                'published_at' => '2025-10-10',
                'title' => ['fr' => 'Campagne de vaccination a Kaffrine', 'en' => 'Vaccination campaign in Kaffrine', 'ar' => 'حملة تطعيم في كافرين'],
                'description' => ['fr' => "Campagne de vaccination infantile ayant couvert 8 localites.", 'en' => 'Child vaccination campaign covering 8 localities.', 'ar' => 'حملة تطعيم للأطفال غطت 8 مناطق.'],
                'location' => ['fr' => 'Kaffrine, Senegal', 'en' => 'Kaffrine, Senegal', 'ar' => 'كافرين، السنغال'],
                'beneficiary_label' => ['fr' => '1 200 enfants', 'en' => '1,200 children', 'ar' => '1200 طفل'],
            ],
            [
                'slug' => 'sante-maternelle-niger',
                'theme' => 'health', 'status' => 'upcoming',
                'goal_amount' => 3400000, 'collected_amount' => 0,
                'cover_image' => '/assets/about.jpeg',
                'published_at' => '2026-08-15',
                'title' => ['fr' => 'Sante maternelle dans le Dosso', 'en' => 'Maternal health in Dosso', 'ar' => 'صحة الأم في دوسو'],
                'description' => ['fr' => "Prise en charge prenatale et suivi pour 200 femmes enceintes.", 'en' => 'Prenatal care and follow-up for 200 pregnant women.', 'ar' => 'رعاية ما قبل الولادة ومتابعة لـ 200 امرأة حامل.'],
                'location' => ['fr' => 'Dosso, Niger', 'en' => 'Dosso, Niger', 'ar' => 'دوسو، النيجر'],
                'beneficiary_label' => ['fr' => '200 femmes', 'en' => '200 women', 'ar' => '200 امرأة'],
            ],
            [
                'slug' => 'tabaski-solidaire-2026',
                'theme' => 'tabaski', 'status' => 'ongoing',
                'goal_amount' => 5000000, 'collected_amount' => 2900000,
                'cover_image' => '/assets/bouffe.jpeg',
                'published_at' => '2026-04-01',
                'title' => ['fr' => 'Tabaski solidaire 2026', 'en' => 'Solidarity Tabaski 2026', 'ar' => 'أضحية التضامن 2026'],
                'description' => ['fr' => "Distribution de viande et repas aux familles vulnerables pour la Tabaski.", 'en' => 'Meat distribution for vulnerable families during Tabaski.', 'ar' => 'توزيع اللحوم والوجبات على الأسر الضعيفة بمناسبة عيد الأضحى.'],
                'location' => ['fr' => 'Mbour, Senegal', 'en' => 'Mbour, Senegal', 'ar' => 'مبور، السنغال'],
                'beneficiary_label' => ['fr' => '400 familles', 'en' => '400 families', 'ar' => '400 عائلة'],
            ],
            [
                'slug' => 'tabaski-solidaire-2025',
                'theme' => 'tabaski', 'status' => 'completed',
                'goal_amount' => 2600000, 'collected_amount' => 2600000,
                'cover_image' => '/assets/bouffe.jpeg',
                'published_at' => '2025-06-15',
                'title' => ['fr' => 'Tabaski solidaire 2025', 'en' => 'Solidarity Tabaski 2025', 'ar' => 'أضحية التضامن 2025'],
                'description' => ['fr' => "Distribution de 300 kits alimentaires et repas de fete.", 'en' => '300 food kits and festive meals distributed.', 'ar' => 'توزيع 300 حصة غذائية ووجبات العيد.'],
                'location' => ['fr' => 'Mbour, Senegal', 'en' => 'Mbour, Senegal', 'ar' => 'مبور، السنغال'],
                'beneficiary_label' => ['fr' => '300 familles', 'en' => '300 families', 'ar' => '300 عائلة'],
            ],
            [
                'slug' => 'tabaski-solidaire-niger-2027',
                'theme' => 'tabaski', 'status' => 'upcoming',
                'goal_amount' => 6200000, 'collected_amount' => 0,
                'cover_image' => '/assets/bouffe.jpeg',
                'published_at' => '2027-04-01',
                'title' => ['fr' => 'Tabaski solidaire Niger 2027', 'en' => 'Solidarity Tabaski Niger 2027', 'ar' => 'أضحية التضامن النيجر 2027'],
                'description' => ['fr' => "Extension aux localites Nigeriennes pour la Tabaski 2027.", 'en' => 'Extension to Nigerien localities for Tabaski 2027.', 'ar' => 'توسعة إلى المناطق النيجرية بمناسبة عيد الأضحى 2027.'],
                'location' => ['fr' => 'Maradi, Niger', 'en' => 'Maradi, Niger', 'ar' => 'مارادي، النيجر'],
                'beneficiary_label' => ['fr' => '500 familles', 'en' => '500 families', 'ar' => '500 عائلة'],
            ],
            [
                'slug' => 'distribution-alimentaire-mbour',
                'theme' => 'food', 'status' => 'ongoing',
                'goal_amount' => 3100000, 'collected_amount' => 1820000,
                'cover_image' => '/assets/bouffe.jpeg',
                'published_at' => '2026-01-20',
                'title' => ['fr' => 'Distribution alimentaire a Mbour', 'en' => 'Food distribution in Mbour', 'ar' => 'توزيع غذائي في مبور'],
                'description' => ['fr' => "Distribution de 350 colis alimentaires aux familles identifiees.", 'en' => '350 food parcels for identified families.', 'ar' => 'توزيع 350 طرداً غذائياً على الأسر المحددة.'],
                'location' => ['fr' => 'Mbour, Senegal', 'en' => 'Mbour, Senegal', 'ar' => 'مبور، السنغال'],
                'beneficiary_label' => ['fr' => '350 familles', 'en' => '350 families', 'ar' => '350 عائلة'],
            ],
            [
                'slug' => 'aide-alimentaire-niger',
                'theme' => 'food', 'status' => 'completed',
                'goal_amount' => 2700000, 'collected_amount' => 2700000,
                'cover_image' => '/assets/bouffe.jpeg',
                'published_at' => '2025-08-20',
                'title' => ['fr' => 'Aide alimentaire Niger', 'en' => 'Food aid Niger', 'ar' => 'مساعدات غذائية النيجر'],
                'description' => ['fr' => "Distribution de 1.5 tonnes de vivres dans 4 villages de la region de Maradi.", 'en' => '1.5 tons of food distributed in 4 villages in Maradi.', 'ar' => 'توزيع 1.5 طن من المواد الغذائية في 4 قرى بمنطقة مارادي.'],
                'location' => ['fr' => 'Maradi, Niger', 'en' => 'Maradi, Niger', 'ar' => 'مارادي، النيجر'],
                'beneficiary_label' => ['fr' => '800 personnes', 'en' => '800 people', 'ar' => '800 شخص'],
            ],
            [
                'slug' => 'securite-alimentaire-thies',
                'theme' => 'food', 'status' => 'upcoming',
                'goal_amount' => 7100000, 'collected_amount' => 0,
                'cover_image' => '/assets/bouffe.jpeg',
                'published_at' => '2026-11-01',
                'title' => ['fr' => 'Securite alimentaire Thies', 'en' => 'Food security Thies', 'ar' => 'الأمن الغذائي ثيس'],
                'description' => ['fr' => "Programme de securite alimentaire sur 6 mois avec stocks de cereales.", 'en' => '6-month food security program with cereal stocks.', 'ar' => 'برنامج الأمن الغذائي لمدة 6 أشهر مع مخزون الحبوب.'],
                'location' => ['fr' => 'Thies, Senegal', 'en' => 'Thies, Senegal', 'ar' => 'ثيس، السنغال'],
                'beneficiary_label' => ['fr' => '1 200 familles', 'en' => '1,200 families', 'ar' => '1200 عائلة'],
            ],
        ];

        foreach ($projects as $data) {
            Project::create($data);
        }
    }
}
